import { Product, Category, Brand } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Smartphones",
    slug: "smartphones",
    description: "Latest flagship phones from top brands",
    image: "/images/categories/smartphones.webp",
    productCount: 48,
  },
  {
    id: "2",
    name: "Cameras",
    slug: "cameras",
    description: "Professional cameras and accessories",
    image: "/images/categories/cameras.webp",
    productCount: 32,
  },
  {
    id: "3",
    name: "Home Appliances",
    slug: "home-appliances",
    description: "Premium home and kitchen appliances",
    image: "/images/categories/home-appliances.webp",
    productCount: 56,
  },
  {
    id: "4",
    name: "Computers",
    slug: "computers",
    description: "Laptops, desktops, and accessories",
    image: "/images/categories/computers.webp",
    productCount: 41,
  },
  {
    id: "5",
    name: "Gaming Consoles",
    slug: "gaming-consoles",
    description: "Consoles, games, and gaming gear",
    image: "/images/categories/gaming-consoles.webp",
    productCount: 27,
  },
];

export const brands: Brand[] = [
  {
    id: "1",
    name: "Samsung",
    slug: "samsung",
    logo: "/images/brands/samsung.svg",
    description: "Leading electronics manufacturer",
  },
  {
    id: "2",
    name: "Apple",
    slug: "apple",
    logo: "/images/brands/apple.svg",
    description: "Premium technology company",
  },
  {
    id: "3",
    name: "Sony",
    slug: "sony",
    logo: "/images/brands/sony.svg",
    description: "Innovative electronics and entertainment",
  },
  {
    id: "4",
    name: "LG",
    slug: "lg",
    logo: "/images/brands/lg.svg",
    description: "Home appliances and electronics",
  },
  {
    id: "5",
    name: "Dell",
    slug: "dell",
    logo: "/images/brands/dell.svg",
    description: "Computer technology solutions",
  },
  {
    id: "6",
    name: "Nikon",
    slug: "nikon",
    logo: "/images/brands/nikon.svg",
    description: "Precision optics and imaging",
  },
];

export const featuredProducts: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy S23 Ultra",
    slug: "samsung-galaxy-s23-ultra",
    description:
      "The ultimate Galaxy experience with built-in S Pen, 200MP camera, and powerful performance.",
    price: 1949,
    compareAtPrice: 2149,
    brand: "Samsung",
    category: "smartphones",
    images: ["/images/products/smartphone-samsung-s23ultra-phantom-front.webp"],
    specs: {
      Display: '6.8" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 2",
      RAM: "12GB",
      Storage: "256GB",
      Camera: "200MP + 12MP + 10MP + 10MP",
      Battery: "5000mAh",
    },
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    isFeatured: true,
    isNew: false,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Apple iPhone 15 Pro Max",
    slug: "apple-iphone-15-pro-max",
    description:
      "Titanium design. A17 Pro chip. 48MP camera system. USB-C. The most powerful iPhone ever.",
    price: 2199,
    brand: "Apple",
    category: "smartphones",
    images: ["/images/products/smartphone-apple-iphone15pro-natural-front.webp"],
    specs: {
      Display: '6.7" Super Retina XDR OLED',
      Processor: "A17 Pro",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "48MP + 12MP + 12MP",
      Battery: "4422mAh",
    },
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    name: "Sony Alpha A7 IV",
    slug: "sony-alpha-a7-iv",
    description:
      "Full-frame hybrid camera with 33MP sensor, 4K 60p video, and advanced autofocus.",
    price: 3499,
    compareAtPrice: 3799,
    brand: "Sony",
    category: "cameras",
    images: ["/images/products/appareilphoto-sony-a7iv-black-front.webp"],
    specs: {
      Sensor: "33MP Full-Frame Exmor R",
      Video: "4K 60fps",
      ISO: "100-51200",
      Stabilization: "5-axis IBIS",
      Autofocus: "759 phase-detection points",
    },
    rating: 4.7,
    reviewCount: 178,
    inStock: true,
    isFeatured: true,
    isNew: false,
    createdAt: "2024-03-10",
  },
  {
    id: "4",
    name: "MacBook Pro 16\" M3 Pro",
    slug: "macbook-pro-16-m3-pro",
    description:
      "Supercharged by M3 Pro chip. 18-hour battery. Stunning Liquid Retina XDR display.",
    price: 3999,
    brand: "Apple",
    category: "computers",
    images: ["/images/products/computer-apple-macbookpro16-space-front.webp"],
    specs: {
      Display: '16.2" Liquid Retina XDR',
      Processor: "M3 Pro",
      RAM: "18GB",
      Storage: "512GB SSD",
      Battery: "Up to 18 hours",
    },
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-04-05",
  },
  {
    id: "5",
    name: "PlayStation 5 Slim",
    slug: "playstation-5-slim",
    description:
      "Smaller design, same power. Experience lightning-fast loading and stunning 4K gaming.",
    price: 799,
    brand: "Sony",
    category: "gaming-consoles",
    images: ["/images/products/console-sony-ps5slim-white-front.webp"],
    specs: {
      CPU: "Custom AMD Zen 2",
      GPU: "AMD RDNA 2",
      Storage: "1TB SSD",
      Resolution: "Up to 8K",
      "Frame Rate": "Up to 120fps",
    },
    rating: 4.8,
    reviewCount: 289,
    inStock: true,
    isFeatured: true,
    isNew: false,
    createdAt: "2024-05-01",
  },
  {
    id: "6",
    name: "Dyson V15 Detect",
    slug: "dyson-v15-detect",
    description:
      "Intelligent cordless vacuum with laser dust detection and LCD screen.",
    price: 1299,
    compareAtPrice: 1499,
    brand: "Dyson",
    category: "home-appliances",
    images: ["/images/products/electromenager-dyson-v15-yellow-front.webp"],
    specs: {
      "Suction Power": "230 AW",
      "Bin Volume": "0.76L",
      "Run Time": "Up to 60 min",
      Filtration: "Whole-machine HEPA",
      Weight: "2.74 kg",
    },
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    isFeatured: true,
    isNew: false,
    createdAt: "2024-02-15",
  },
  {
    id: "7",
    name: "LG OLED C3 65\"",
    slug: "lg-oled-c3-65",
    description:
      "Self-lit OLED pixels deliver perfect black, incredible contrast, and brilliant colors.",
    price: 3299,
    compareAtPrice: 3699,
    brand: "LG",
    category: "home-appliances",
    images: ["/images/products/electromenager-lg-oledc3-black-front.webp"],
    specs: {
      Display: '65" OLED evo',
      Resolution: "4K",
      "Refresh Rate": "120Hz",
      HDMI: "4x HDMI 2.1",
      Smart: "webOS 23",
    },
    rating: 4.7,
    reviewCount: 167,
    inStock: true,
    isFeatured: false,
    isNew: true,
    createdAt: "2024-03-20",
  },
  {
    id: "8",
    name: "Nikon Z8",
    slug: "nikon-z8",
    description:
      "Professional full-frame mirrorless camera with 45.7MP and 8K video.",
    price: 5499,
    brand: "Nikon",
    category: "cameras",
    images: ["/images/products/appareilphoto-nikon-z8-black-front.webp"],
    specs: {
      Sensor: "45.7MP Full-Frame",
      Video: "8K 60fps",
      ISO: "64-25600",
      Stabilization: "5-axis VR",
      Autofocus: "493-point hybrid AF",
    },
    rating: 4.8,
    reviewCount: 92,
    inStock: true,
    isFeatured: false,
    isNew: true,
    createdAt: "2024-04-15",
  },
];